# Generated by Django 3.0.1 on 2020-04-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('poster', models.ImageField(null=True, upload_to='event_poster')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Final Year')], default=2)),
                ('department', models.CharField(choices=[('OFFICE BEARERS', 'Office Bearers'), ('MANAGEMENT', 'Management'), ('AUTOMOBILE', 'Automobile'), ('MANUAL', 'Manual'), ('WEBD', 'Web Developement'), ('GRAPHICS', 'Graphics and Photography'), ('NDORS', 'NDORS')], default='FIRST', max_length=20)),
                ('photo', models.ImageField(null=True, upload_to='profile_pics')),
            ],
        ),
    ]
