# Generated by Django 3.0.5 on 2020-05-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20200415_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-year',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default='2020-05-11 05:23'),
            preserve_default=False,
        ),
    ]
