# Generated by Django 2.0.2 on 2020-04-02 14:53

import Website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_auto_20200402_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_pics', validators=[Website.models.validate_image_size]),
        ),
    ]
