# Generated by Django 3.0.1 on 2020-04-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20200402_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
