# Generated by Django 3.0.5 on 2020-05-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20200511_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timestamp',
        ),
    ]
