# Generated by Django 3.0.1 on 2020-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('online', 'ONLINE'), ('offline', 'OFFLINE')], default='offline', max_length=50),
        ),
    ]
