# Generated by Django 3.0.5 on 2020-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_remove_profile_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default='2020-04-11 05:36:00'),
            preserve_default=False,
        ),
    ]
