# Generated by Django 3.0.1 on 2020-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_event_type_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('OFFICE BEARERS', 'Office Bearers'), ('MANAGEMENT', 'Management'), ('TECHNICAL', 'Technical'), ('WEBD', 'Web Developement'), ('GRAPHICS', 'Graphics and Photography'), ('NDORS', 'NDORS')], default='FIRST', max_length=20),
        ),
    ]
