# Generated by Django 3.0.5 on 2020-07-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_profile_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timestamp',
        ),
    ]
