# Generated by Django 3.0.5 on 2020-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_auto_20200406_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('VICE PRESIDENT', 'Vice President'), ('GENERAL SECRETARY', 'General Secretary'), ('TREASURER', 'Treasurer'), ('NONE', 'None')], default='None', max_length=20),
        ),
    ]
