# Generated by Django 3.0.1 on 2020-04-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_auto_20200406_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.CharField(choices=[(1, 'President'), (2, 'Vice President'), (3, 'General Secretary'), (4, 'Treasurer'), (5, 'None')], default='FIRST', max_length=20),
        ),
    ]
