# Generated by Django 3.0.1 on 2020-04-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_auto_20200408_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('VICE PRESIDENT', 'Vice President'), ('GENERAL SECRETARY', 'General Secretary'), ('TREASURER', 'Treasurer'), ('NONE', 'None')], default='None', max_length=20),
        ),
    ]
