# Generated by Django 2.0.2 on 2020-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_blog',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='bprofile_pics'),
        ),
    ]
